Repository ITA-OneByte/OneByte-BE, pull requests merged in 2024-11, with the labels that each got.

#12 [feat] 엔티티 관계 정의 및 필드 설정 #11
  src/main/java/classfit/example/classfit/common/AttendanceStatus.java
  src/main/java/classfit/example/classfit/common/Gender.java
  src/main/java/classfit/example/classfit/common/LoginType.java
  src/main/java/classfit/example/classfit/common/MemberStatus.java
  src/main/java/classfit/example/classfit/domain/Attendance.java
  src/main/java/classfit/example/classfit/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/domain/MainClass.java
  src/main/java/classfit/example/classfit/domain/Member.java
  src/main/java/classfit/example/classfit/domain/Student.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
Labels: Feat, Chore

#14 [chore] Default branch 수정
  src/main/java/classfit/example/classfit/common/AttendanceStatus.java
  src/main/java/classfit/example/classfit/common/Gender.java
  src/main/java/classfit/example/classfit/common/LoginType.java
  src/main/java/classfit/example/classfit/common/MemberStatus.java
  src/main/java/classfit/example/classfit/domain/Attendance.java
  src/main/java/classfit/example/classfit/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/domain/MainClass.java
  src/main/java/classfit/example/classfit/domain/Member.java
  src/main/java/classfit/example/classfit/domain/Student.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
Labels: Chore

#16 [Feat] 클래스 API
  src/main/java/classfit/example/classfit/ClassfitApplication.java
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/controller/SubClassController.java
  src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
  src/main/java/classfit/example/classfit/category/dto/request/SubClassRequest.java
  src/main/java/classfit/example/classfit/category/dto/response/MainClassResponse.java
  src/main/java/classfit/example/classfit/category/dto/response/SubClassResponse.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRespository.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
  src/main/java/classfit/example/classfit/common/ApiResponse.java
  src/main/java/classfit/example/classfit/domain/MainClass.java
  src/main/java/classfit/example/classfit/domain/Member.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
  src/main/java/classfit/example/classfit/exception/ClassfitException.java
  src/main/java/classfit/example/classfit/exception/ClassfitExceptionControllerAdivce.java
  src/main/java/classfit/example/classfit/member/MemberRepository.java
Labels: Feat

#17 [Feat] 클래스 API
  src/main/java/classfit/example/classfit/ClassfitApplication.java
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/controller/SubClassController.java
  src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
  src/main/java/classfit/example/classfit/category/dto/request/SubClassRequest.java
  src/main/java/classfit/example/classfit/category/dto/response/MainClassResponse.java
  src/main/java/classfit/example/classfit/category/dto/response/SubClassResponse.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRespository.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
  src/main/java/classfit/example/classfit/common/ApiResponse.java
  src/main/java/classfit/example/classfit/domain/MainClass.java
  src/main/java/classfit/example/classfit/domain/Member.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
  src/main/java/classfit/example/classfit/exception/ClassfitException.java
  src/main/java/classfit/example/classfit/exception/ClassfitExceptionControllerAdivce.java
  src/main/java/classfit/example/classfit/member/MemberRepository.java
Labels: Feat

#20 [Feat] 클래스 정보 조회 API
  src/main/java/classfit/example/classfit/category/controller/ClassInfoController.java
  src/main/java/classfit/example/classfit/category/dto/response/ClassInfoResponse.java
  src/main/java/classfit/example/classfit/category/dto/response/SubClassResponse.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRespository.java
  src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
Labels: Feat

#23 [feat] 학생 정보 API
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/class_student/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/common/ApiResponse.java
  src/main/java/classfit/example/classfit/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/domain/Student.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
  src/main/java/classfit/example/classfit/student/controller/StudentControllerImpl.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/request/UpdateStudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/response/StudentResponse.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Feat, Refactor, Chore

#22 [feat] 메인 클래스 조회기능 추가
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/dto/response/AllMainClassResponse.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
Labels: Feat

#28 [Feat] 단체문자 API
  build.gradle
  src/main/java/classfit/example/classfit/domain/Member.java
  src/main/java/classfit/example/classfit/domain/Student.java
  src/main/java/classfit/example/classfit/sms/controller/SendMessageController.java
  src/main/java/classfit/example/classfit/sms/dto/SendRequest.java
  src/main/java/classfit/example/classfit/sms/service/SmsService.java
  src/main/java/classfit/example/classfit/student/StudentRepository.java
Labels: Feat

#24 [Feat] 출결 관련 API
  build.gradle
  src/main/java/classfit/example/classfit/ClassfitApplication.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
  src/main/java/classfit/example/classfit/attendance/dto/request/AttendanceStatusUpdateRequest.java
  src/main/java/classfit/example/classfit/attendance/dto/request/StudentAttendanceUpdateRequest.java
  src/main/java/classfit/example/classfit/attendance/dto/response/AttendanceResponse.java
  src/main/java/classfit/example/classfit/attendance/dto/response/StudentAttendanceResponse.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
  src/main/java/classfit/example/classfit/attendance/service/util/DateRangeUtil.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/domain/Attendance.java
  src/main/java/classfit/example/classfit/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/domain/Student.java
  src/main/java/classfit/example/classfit/domain/SubClass.java
  src/main/java/classfit/example/classfit/exception/ClassfitException.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
  src/test/java/classfit/example/classfit/common/util/DateRangeUtilTest.java
Labels: Feat

#36 [Feat] 학생 다중 삭제 API (다중 삭제)
  src/main/java/classfit/example/classfit/student/controller/StudentControllerImpl.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
  src/main/java/classfit/example/classfit/student/dto/response/StudentResponse.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Feat, Refactor

#40 dev -> main
  src/main/java/classfit/example/classfit/domain/MainClass.java
Labels: Refactor

#41 dev -> main
  build.gradle
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
Labels: Feat

#62 [Fix] Request DTO 유효성 검증 해결
  build.gradle
  src/main/java/classfit/example/classfit/common/validation/EnumValidator.java
  src/main/java/classfit/example/classfit/common/validation/EnumValue.java
  src/main/java/classfit/example/classfit/common/validation/NotBlankNullable.java
  src/main/java/classfit/example/classfit/common/validation/NotBlankNullableValidator.java
  src/main/java/classfit/example/classfit/exception/ClassfitExceptionControllerAdivce.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Fix

#64 [Refactor] DDD 폴더 구조
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
  src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
  src/main/java/classfit/example/classfit/attendance/domain/AttendanceStatus.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
  src/main/java/classfit/example/classfit/category/domain/MainClass.java
  src/main/java/classfit/example/classfit/category/domain/SubClass.java
  src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
  src/main/java/classfit/example/classfit/category/dto/request/SubClassRequest.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRespository.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
  src/main/java/classfit/example/classfit/classStudent/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/common/ApiResponse.java
  src/main/java/classfit/example/classfit/common/Gender.java
  src/main/java/classfit/example/classfit/common/domain/BaseEntity.java
  src/main/java/classfit/example/classfit/common/domain/ResultType.java
  src/main/java/classfit/example/classfit/common/exception/ClassfitException.java
  src/main/java/classfit/example/classfit/common/exception/ClassfitExceptionControllerAdivce.java
  src/main/java/classfit/example/classfit/member/MemberRepository.java
  src/main/java/classfit/example/classfit/member/domain/Gender.java
  src/main/java/classfit/example/classfit/member/domain/LoginType.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/domain/MemberStatus.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/sms/service/SmsService.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
  src/main/java/classfit/example/classfit/student/dto/response/StudentInfoResponse.java
  src/main/java/classfit/example/classfit/student/dto/response/StudentResponse.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
  src/main/java/classfit/example/classfit/util/DateRangeUtil.java
  src/test/java/classfit/example/classfit/common/util/DateRangeUtilTest.java
Labels: Refactor

#72 [Feat] 이메일 전송 및 인증코드 검증 API
  build.gradle
  src/main/java/classfit/example/classfit/ClassfitApplication.java
  src/main/java/classfit/example/classfit/config/MailConfig.java
  src/main/java/classfit/example/classfit/config/RedisConfig.java
  src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
  src/main/java/classfit/example/classfit/mail/dto/request/EmailAuthRequest.java
  src/main/java/classfit/example/classfit/mail/dto/request/EmailAuthVerifyRequest.java
  src/main/java/classfit/example/classfit/mail/dto/response/EmailAuthResponse.java
  src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/util/RedisUtil.java
  src/main/resources/templates/mail.html
Labels: Feat

#75 [Refactor] HTTP 메서드 수정
  src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
Labels: Refactor

#76 [Refactor] 배포 반영, HTTP 메서드 수정
  src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
Labels: Refactor

#78 [Feat] 학원 Entity 추가 및 멤버 Entity 필드 수정
  src/main/java/classfit/example/classfit/academy/domain/Academy.java
  src/main/java/classfit/example/classfit/member/domain/Gender.java
  src/main/java/classfit/example/classfit/member/domain/LoginType.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/student/domain/Gender.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
  src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
  src/main/java/classfit/example/classfit/student/dto/response/StudentInfoResponse.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Feat, Refactor

#84 [feat] 회원가입 기능 구현
  src/main/java/classfit/example/classfit/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/dto/request/MemberRequest.java
  src/main/java/classfit/example/classfit/member/dto/response/MemberResponse.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
Labels: Feat

#83 [Fix] 출결 데이터 생성
  src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
  src/main/java/classfit/example/classfit/attendance/dto/response/AttendanceResponse.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
  src/test/java/classfit/example/classfit/attendance/service/AttendanceSchedulingServiceTest.java
Labels: Fix

#86 [Feat] 학원 등록 및 학원 코드 생성 API
  src/main/java/classfit/example/classfit/academy/controller/AcademyController.java
  src/main/java/classfit/example/classfit/academy/domain/Academy.java
  src/main/java/classfit/example/classfit/academy/dto/request/AcademyRequest.java
  src/main/java/classfit/example/classfit/academy/dto/response/AcademyResponse.java
  src/main/java/classfit/example/classfit/academy/repository/AcademyRepository.java
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
  src/main/java/classfit/example/classfit/util/CodeUtil.java
Labels: Feat

#89 [Feat] 로그인 기능 구현
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/auth/controller/AuthController.java
  src/main/java/classfit/example/classfit/auth/dto/request/CustomUserDetails.java
  src/main/java/classfit/example/classfit/auth/dto/request/UserRequest.java
  src/main/java/classfit/example/classfit/auth/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/filter/JWTFilter.java
  src/main/java/classfit/example/classfit/auth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/jwt/JWTUtil.java
  src/main/java/classfit/example/classfit/auth/service/AuthService.java
  src/main/java/classfit/example/classfit/auth/service/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/common/util/CodeUtil.java
  src/main/java/classfit/example/classfit/common/util/DateRangeUtil.java
  src/main/java/classfit/example/classfit/common/util/RedisUtil.java
  src/main/java/classfit/example/classfit/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/config/SwaggerConfig.java
  src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/dto/request/MemberRequest.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
  src/test/java/classfit/example/classfit/common/util/DateRangeUtilTest.java
Labels: Feat, Refactor
