Repository ITA-OneByte/OneByte-BE, pull requests merged in 2024-12, with the labels that each got.

#92 [Feat] 출결 통계
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
  src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
  src/main/java/classfit/example/classfit/attendance/dto/response/StatisticsDateResponse.java
  src/main/java/classfit/example/classfit/attendance/dto/response/StatisticsMemberResponse.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
  src/main/java/classfit/example/classfit/classStudent/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Feat

#96 [Refactor] Redis Auto-Configuration 사용
  src/main/java/classfit/example/classfit/common/util/RedisUtil.java
  src/main/java/classfit/example/classfit/config/RedisConfig.java
Labels: Refactor

#98 [Refactor] CustomAuthenticationProvider와 CustomAuthenticationToken 추가 및 리팩토링
  src/main/java/classfit/example/classfit/auth/dto/request/CustomAuthenticationToken.java
  src/main/java/classfit/example/classfit/auth/security/CustomAuthenticationProvider.java
  src/main/java/classfit/example/classfit/auth/security/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTUtil.java
  src/main/java/classfit/example/classfit/auth/service/AuthService.java
  src/main/java/classfit/example/classfit/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/config/SwaggerConfig.java
  src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
Labels: Feat, Refactor

#100 [Feat] 로그인 사용자 어노테이션 기반 처리
  src/main/java/classfit/example/classfit/auth/annotation/AuthMember.java
  src/main/java/classfit/example/classfit/auth/annotation/AuthMemberArgumentResolver.java
  src/main/java/classfit/example/classfit/auth/security/CustomAuthenticationProvider.java
  src/main/java/classfit/example/classfit/auth/security/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/auth/security/config/SecurityUtil.java
  src/main/java/classfit/example/classfit/auth/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTFilter.java
  src/main/java/classfit/example/classfit/auth/security/provider/CustomAuthenticationProvider.java
  src/main/java/classfit/example/classfit/auth/security/provider/CustomAuthenticationToken.java
  src/main/java/classfit/example/classfit/auth/security/provider/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/auth/security/provider/CustomUserDetails.java
  src/main/java/classfit/example/classfit/common/config/MailConfig.java
  src/main/java/classfit/example/classfit/common/config/SwaggerConfig.java
  src/main/java/classfit/example/classfit/common/config/SwaggerController.java
  src/main/java/classfit/example/classfit/common/config/WebConfig.java
  src/main/java/classfit/example/classfit/config/SwaggerController.java
Labels: Feat, Refactor

#101 [Feat] 출결 통계 세부 정보 조회
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
  src/main/java/classfit/example/classfit/attendance/dto/response/StatisticsMemberResponse.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
Labels: Feat

#103 [Feat] 로그아웃 기능 구현
  src/main/java/classfit/example/classfit/auth/controller/AuthController.java
  src/main/java/classfit/example/classfit/auth/service/AuthService.java
  src/main/java/classfit/example/classfit/common/config/WebConfig.java
Labels: Refactor

#106 [Feat] 비밀번호 수정 API
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/service/AuthService.java
  src/main/java/classfit/example/classfit/common/util/EmailUtil.java
  src/main/java/classfit/example/classfit/common/util/RedisUtil.java
  src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
  src/main/java/classfit/example/classfit/mail/dto/request/EmailAuthPurpose.java
  src/main/java/classfit/example/classfit/mail/dto/request/EmailAuthRequest.java
  src/main/java/classfit/example/classfit/mail/dto/request/EmailAuthVerifyRequest.java
  src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/dto/request/MemberPasswordRequest.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
  src/main/resources/templates/mail.html
Labels: Feat

#105 Feat/94 성적관리 API
  src/main/java/classfit/example/classfit/config/RedisConfig.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/studentExam/controller/ExamController.java
  src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
  src/main/java/classfit/example/classfit/studentExam/domain/ExamRepository.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
  src/main/java/classfit/example/classfit/studentExam/dto/process/ExamClassStudent.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/CreateExamRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/FindExamRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/UpdateExamRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/UpdateStudentScoreRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/CreateExamResponse.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/FindExamResponse.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/ShowExamClassStudentResponse.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/ShowExamDetailResponse.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/UpdateExamResponse.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Feat

#109 [Feat] 기존 학원 합류 API
  src/main/java/classfit/example/classfit/academy/controller/AcademyController.java
  src/main/java/classfit/example/classfit/academy/domain/Academy.java
  src/main/java/classfit/example/classfit/academy/dto/request/AcademyCreateRequest.java
  src/main/java/classfit/example/classfit/academy/dto/request/AcademyJoinRequest.java
  src/main/java/classfit/example/classfit/academy/repository/AcademyRepository.java
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/auth/security/config/SecurityUtil.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomAuthenticationProvider.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomAuthenticationToken.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomUserDetails.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTFilter.java
  src/main/java/classfit/example/classfit/classStudent/domain/ClassStudent.java
  src/main/java/classfit/example/classfit/config/RedisConfig.java
  src/main/java/classfit/example/classfit/invitation/domain/Invitation.java
  src/main/java/classfit/example/classfit/invitation/domain/InvitationStatus.java
  src/main/java/classfit/example/classfit/invitation/repository/InvitationRepository.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/dto/request/MemberPasswordRequest.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Feat, Refactor

#115 [CI/CD] Docker Compose 기반의 Git Action 파이프라인 구축
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/common/config/RedisConfig.java
  src/main/java/classfit/example/classfit/common/config/SwaggerController.java
  src/main/java/classfit/example/classfit/common/util/RedisUtil.java
Labels: Ci

#120 [CI/CD] AWS EC2 + Docker + Self-hosted Runner CICD 파이프 라인 구축
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/common/config/SwaggerController.java
Labels: Ci

#125 [refactor] 스웨거 태그 수정 및 엔드포인트 수정
  src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/student/controller/StudentControllerImpl.java
Labels: Refactor, Chore

#127 [refactor] workflow step 수정
  .github/workflows/gradle.yml
Labels: Refactor
