Repository ITA-OneByte/OneByte-BE, pull requests merged in 2025-01, with the labels that each got.

#132 [Feat] 학습리포트 api
  src/main/java/classfit/example/classfit/attendance/dto/process/AttendanceInfo.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
  src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/scoreReport/controller/ScoreReportController.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
  src/main/java/classfit/example/classfit/scoreReport/dto/process/ReportExam.java
  src/main/java/classfit/example/classfit/scoreReport/dto/request/CreateReportRequest.java
  src/main/java/classfit/example/classfit/scoreReport/dto/request/SentStudentOpinionRequest.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/CreateReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/FindClassStudent.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/FindReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/SentStudentOpinionResponse.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/ShowStudentReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
  src/main/java/classfit/example/classfit/student/dto/StudentList.java
  src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
  src/main/java/classfit/example/classfit/studentExam/dto/process/ExamHistory.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Feat

#141 [refactor] 성적관리 api 프론트 요구사항 수정
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/UpdateStudentScoreRequest.java
Labels: Refactor

#138 [Feat] 일정 관리
  src/main/java/classfit/example/classfit/calendarCategory/controller/CalendarCategoryController.java
  src/main/java/classfit/example/classfit/calendarCategory/domain/CalendarCategory.java
  src/main/java/classfit/example/classfit/calendarCategory/domain/CategoryColor.java
  src/main/java/classfit/example/classfit/calendarCategory/dto/request/CalendarCategoryCreateRequest.java
  src/main/java/classfit/example/classfit/calendarCategory/dto/request/CalendarCategoryUpdateRequest.java
  src/main/java/classfit/example/classfit/calendarCategory/dto/response/CalendarCategoryCreateResponse.java
  src/main/java/classfit/example/classfit/calendarCategory/dto/response/CalendarCategoryListResponse.java
  src/main/java/classfit/example/classfit/calendarCategory/dto/response/CalendarCategoryResponse.java
  src/main/java/classfit/example/classfit/calendarCategory/repository/CalendarCategoryRepository.java
  src/main/java/classfit/example/classfit/calendarCategory/service/CalendarCategoryService.java
  src/main/java/classfit/example/classfit/common/exception/ClassfitException.java
  src/main/java/classfit/example/classfit/event/controller/EventController.java
  src/main/java/classfit/example/classfit/event/domain/Event.java
  src/main/java/classfit/example/classfit/event/domain/EventRepeatType.java
  src/main/java/classfit/example/classfit/event/domain/EventType.java
  src/main/java/classfit/example/classfit/event/dto/request/EventCreateRequest.java
  src/main/java/classfit/example/classfit/event/dto/request/EventModalRequest.java
  src/main/java/classfit/example/classfit/event/dto/response/EventMontylyResponse.java
  src/main/java/classfit/example/classfit/event/dto/response/EventResponse.java
  src/main/java/classfit/example/classfit/event/repository/EventRepository.java
  src/main/java/classfit/example/classfit/event/service/EventService.java
  src/main/java/classfit/example/classfit/eventMember/domain/EventMember.java
  src/main/java/classfit/example/classfit/member/dto/response/AcademyMemberResponse.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
  src/main/java/classfit/example/classfit/memberCalendar/domain/CalendarType.java
  src/main/java/classfit/example/classfit/memberCalendar/domain/MemberCalendar.java
  src/main/java/classfit/example/classfit/memberCalendar/repository/MemberCalendarRepository.java
  src/main/java/classfit/example/classfit/memberCalendar/service/MemberCalendarService.java
Labels: Feat

#145 [Feat] 마이페이지 관련 API 구현
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/member/dto/request/MemberUpdateInfoRequest.java
  src/main/java/classfit/example/classfit/member/dto/response/MemberInfoResponse.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
Labels: Feat

#151 [Feat] 날짜 기반 로그 파일 롤링 구현
  .github/workflows/gradle.yml
  src/main/resources/logback-spring.xml
Labels: Feat, Refactor, Ci

#154 [refactor] 성적관리 API 프론트 요구사항 수정
  src/main/java/classfit/example/classfit/scoreReport/dto/response/CreateReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
  src/main/java/classfit/example/classfit/student/dto/StudentList.java
  src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
  src/main/java/classfit/example/classfit/studentExam/dto/process/ExamClassStudent.java
  src/main/java/classfit/example/classfit/studentExam/dto/process/ExamStudent.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/UpdateStudentScoreRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/FindExamResponse.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Refactor

#136 [feat] 드라이브
  build.gradle
  src/main/java/classfit/example/classfit/common/config/S3Config.java
  src/main/java/classfit/example/classfit/drive/controller/DriveController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
  src/main/java/classfit/example/classfit/drive/domain/DriveType.java
  src/main/java/classfit/example/classfit/drive/domain/FileType.java
  src/main/java/classfit/example/classfit/drive/dto/response/FileInfo.java
  src/main/java/classfit/example/classfit/drive/service/DriveDownloadService.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Feat

#160 [Feat] 드라이브 휴지통 기능 및 삭제 기능 구현
  .gitignore
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/controller/DriveController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveTrashController.java
  src/main/java/classfit/example/classfit/drive/domain/FileType.java
  src/main/java/classfit/example/classfit/drive/dto/response/FileResponse.java
  src/main/java/classfit/example/classfit/drive/service/DriveDeleteService.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
  src/main/java/classfit/example/classfit/drive/service/DriveRestoreService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Feat, Refactor

#165 [Refactor] 드라이브 프론트 요구사항 반영
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/controller/DriveController.java
  src/main/java/classfit/example/classfit/drive/domain/FileType.java
  src/main/java/classfit/example/classfit/drive/dto/response/FileInfo.java
  src/main/java/classfit/example/classfit/drive/dto/response/FileResponse.java
  src/main/java/classfit/example/classfit/drive/service/DriveDownloadService.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Refactor, Fix

#171 [Refactor] 일정관리 프론트 요구사항 반영
  src/main/java/classfit/example/classfit/calendarCategory/repository/CalendarCategoryRepository.java
  src/main/java/classfit/example/classfit/event/controller/EventController.java
  src/main/java/classfit/example/classfit/event/domain/Event.java
  src/main/java/classfit/example/classfit/event/dto/request/EventCreateRequest.java
  src/main/java/classfit/example/classfit/event/dto/request/EventModalRequest.java
  src/main/java/classfit/example/classfit/event/repository/EventRepository.java
  src/main/java/classfit/example/classfit/event/service/EventService.java
Labels: Refactor, Fix

#173 [fix] 학습리포트 쿼리 수정
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
Labels: Fix

#175 [Refactor] 일정관리 리팩토링
  src/main/java/classfit/example/classfit/event/domain/Event.java
  src/main/java/classfit/example/classfit/event/service/EventCreateService.java
  src/main/java/classfit/example/classfit/event/service/EventGetService.java
  src/main/java/classfit/example/classfit/event/service/EventRepeatService.java
  src/main/java/classfit/example/classfit/event/service/EventService.java
  src/main/java/classfit/example/classfit/event/service/EventUpdateService.java
Labels: Refactor

#178 [Refactor] 인증/인가 관련 코드 리팩토링
  src/main/java/classfit/example/classfit/auth/annotation/AuthMemberArgumentResolver.java
  src/main/java/classfit/example/classfit/auth/dto/request/UserRequest.java
  src/main/java/classfit/example/classfit/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/classfit/example/classfit/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomAuthenticationProvider.java
  src/main/java/classfit/example/classfit/auth/security/custom/CustomUserDetailService.java
  src/main/java/classfit/example/classfit/auth/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTUtil.java
  src/main/java/classfit/example/classfit/auth/service/AuthService.java
  src/main/java/classfit/example/classfit/common/ApiResponse.java
  src/main/java/classfit/example/classfit/common/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/common/exception/ClassfitAuthException.java
  src/main/java/classfit/example/classfit/common/util/CookieUtil.java
  src/main/java/classfit/example/classfit/common/util/SecurityUtil.java
  src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
Labels: Feat, Refactor

#180 [Feat] 드라이브 폴더 삭제 API 구현
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
Labels: Feat, Refactor, Fix

#183 [refactor] 월별 일정 조회 시 카테고리 색상 추가 #182
  src/main/java/classfit/example/classfit/event/dto/response/EventMontylyResponse.java
  src/main/java/classfit/example/classfit/event/service/EventGetService.java
Labels: Refactor

#184 [Refactor] 드라이브 프론트 요구사항
  src/main/java/classfit/example/classfit/drive/controller/DriveFileController.java
  src/main/java/classfit/example/classfit/drive/service/DriveDownloadService.java
Labels: Refactor, Fix

#189 [Refactor] 일정관리 프론트
  src/main/java/classfit/example/classfit/event/controller/EventController.java
  src/main/java/classfit/example/classfit/event/domain/Event.java
  src/main/java/classfit/example/classfit/event/dto/response/EventModalResponse.java
  src/main/java/classfit/example/classfit/event/service/EventGetService.java
  src/main/java/classfit/example/classfit/event/service/EventRepeatService.java
  src/main/java/classfit/example/classfit/event/service/EventService.java
Labels: Feat, Refactor

#191 [refactor] 학원 검증 로직 추가, 연관관계 수정
  src/main/java/classfit/example/classfit/category/domain/MainClass.java
  src/main/java/classfit/example/classfit/category/domain/SubClass.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/scoreReport/controller/ScoreReportController.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
  src/main/java/classfit/example/classfit/studentExam/domain/ExamRepository.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/FindExamResponse.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Refactor

#196 [Fix] 학생 정보 조회 오류 수정
  src/main/java/classfit/example/classfit/member/domain/Member.java
  src/main/java/classfit/example/classfit/student/controller/StudentController.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
Labels: Refactor, Fix

#197 [ Fix] 드라이브 프론트 요구사항
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Refactor, Fix

#199 [fix] 메인클래스와 멤버 매칭 메서드 수정
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
Labels: Fix

#200 [fix] 메인클래스와 멤버 매칭 메서드 수정
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
  src/main/java/classfit/example/classfit/category/service/SubClassService.java
Labels: Fix

#202 [Feat] 메인 클래스 수정 API 구현
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
Labels: Feat, Refactor

#203 [Release] 메인 클래스 추가 API 배포
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
  src/main/java/classfit/example/classfit/category/service/MainClassService.java
Labels: Feat, Refactor

#204 [Fix] 드라이브 folderPath 오류 해결
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
Labels: Fix

#206 [fix] 파일 조회 오류 해결 #181
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
Labels: Fix

#212 [fix] 시험지 전체조회시 에러 수정
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/category/controller/ClassInfoController.java
  src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
  src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Fix

#215 [Fix] 드라이브 휴지통 관련 API 로직 개선
  build.gradle
  src/main/java/classfit/example/classfit/common/config/S3Config.java
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveTrashController.java
  src/main/java/classfit/example/classfit/drive/service/DriveDeleteService.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveRestoreService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Refactor, Fix

#216 [Release] 드라이브 휴지통 API 로직 변경
  build.gradle
  src/main/java/classfit/example/classfit/common/config/S3Config.java
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveTrashController.java
  src/main/java/classfit/example/classfit/drive/service/DriveDeleteService.java
  src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
  src/main/java/classfit/example/classfit/drive/service/DriveRestoreService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Add

#221 [Fix] 출결 조회 conflict 해결
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
Labels: Fix

#224 [Fix] 직원 초대 API 에러 수정
  src/main/java/classfit/example/classfit/academy/controller/AcademyController.java
  src/main/java/classfit/example/classfit/academy/repository/AcademyRepository.java
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/common/config/SecurityConfig.java
  src/main/java/classfit/example/classfit/invitation/repository/InvitationRepository.java
  src/main/java/classfit/example/classfit/invitation/service/InvitationService.java
  src/main/java/classfit/example/classfit/mail/handler/InvitationHandler.java
  src/main/java/classfit/example/classfit/mail/service/EmailService.java
Labels: Fix

#229 [Fix] 출결관리 관련 에러 수정
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
Labels: Fix

#234 [fix] 성적관리 관련 에러 수정
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
  src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
  src/main/java/classfit/example/classfit/studentExam/domain/ExamRepository.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
  src/main/java/classfit/example/classfit/studentExam/dto/process/ExamHistory.java
  src/main/java/classfit/example/classfit/studentExam/dto/request/FindExamRequest.java
  src/main/java/classfit/example/classfit/studentExam/dto/response/ShowExamDetailResponse.java
  src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
Labels: Fix

#242 [Fix] 일정관련 관련 에러 수정
  src/main/java/classfit/example/classfit/calendarCategory/repository/CalendarCategoryRepository.java
  src/main/java/classfit/example/classfit/calendarCategory/service/CalendarCategoryService.java
  src/main/java/classfit/example/classfit/event/repository/EventRepository.java
  src/main/java/classfit/example/classfit/event/service/EventGetService.java
Labels: Fix

#248 [Fix] 드라이브 폴더 크기 변경
  src/main/java/classfit/example/classfit/common/util/DriveUtil.java
  src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
  src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
  src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Labels: Fix

#250 [fix] 학습리포트 작성자 추가
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
  src/main/java/classfit/example/classfit/scoreReport/dto/request/CreateReportRequest.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/CreateReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/FindAllReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/dto/response/FindReportResponse.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
Labels: Fix

#231 [Fix] 학생 삭제
  src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
  src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
  src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
  src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
  src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
  src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
  src/main/java/classfit/example/classfit/student/controller/StudentController.java
  src/main/java/classfit/example/classfit/student/domain/Student.java
  src/main/java/classfit/example/classfit/student/service/StudentService.java
  src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
Labels: Fix

#259 [Refactor] 도메인별 Swagger 설정을 위한 컨트롤러 인터페이스 구현
  src/main/java/classfit/example/classfit/academy/controller/AcademyController.java
  src/main/java/classfit/example/classfit/academy/controller/docs/AcademyControllerDocs.java
  src/main/java/classfit/example/classfit/academy/service/AcademyService.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
  src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
  src/main/java/classfit/example/classfit/attendance/controller/docs/AttendanceControllerDocs.java
  src/main/java/classfit/example/classfit/attendance/controller/docs/AttendanceExportControllerDocs.java
  src/main/java/classfit/example/classfit/attendance/controller/docs/AttendanceStatisticsControllerDocs.java
  src/main/java/classfit/example/classfit/auth/controller/AuthController.java
  src/main/java/classfit/example/classfit/auth/controller/docs/AuthControllerDocs.java
  src/main/java/classfit/example/classfit/auth/exception/CustomAccessDeniedHandler.java
  src/main/java/classfit/example/classfit/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
  src/main/java/classfit/example/classfit/auth/security/jwt/JWTFilter.java
  src/main/java/classfit/example/classfit/calendarCategory/controller/CalendarCategoryController.java
  src/main/java/classfit/example/classfit/calendarCategory/controller/docs/CalendarCategoryControllerDocs.java
  src/main/java/classfit/example/classfit/category/controller/ClassInfoController.java
  src/main/java/classfit/example/classfit/category/controller/MainClassController.java
  src/main/java/classfit/example/classfit/category/controller/SubClassController.java
  src/main/java/classfit/example/classfit/category/controller/docs/ClassInfoControllerDocs.java
  src/main/java/classfit/example/classfit/category/controller/docs/MainClassControllerDocs.java
  src/main/java/classfit/example/classfit/category/controller/docs/SubClassControllerDocs.java
  src/main/java/classfit/example/classfit/common/CustomApiResponse.java
  src/main/java/classfit/example/classfit/common/exception/ClassfitExceptionControllerAdivce.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFileController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveGetController.java
  src/main/java/classfit/example/classfit/drive/controller/DriveTrashController.java
  src/main/java/classfit/example/classfit/drive/controller/docs/DriveFileControllerDocs.java
  src/main/java/classfit/example/classfit/drive/controller/docs/DriveFolderControllerDocs.java
  src/main/java/classfit/example/classfit/drive/controller/docs/DriveGetControllerDocs.java
  src/main/java/classfit/example/classfit/drive/controller/docs/DriveTrashControllerDocs.java
  src/main/java/classfit/example/classfit/event/controller/EventController.java
  src/main/java/classfit/example/classfit/event/controller/docs/EventControllerDocs.java
  src/main/java/classfit/example/classfit/invitation/controller/InvitationController.java
  src/main/java/classfit/example/classfit/invitation/controller/docs/InvitationControllerDocs.java
  src/main/java/classfit/example/classfit/mail/controller/EmailController.java
  src/main/java/classfit/example/classfit/mail/controller/docs/EmailControllerDocs.java
  src/main/java/classfit/example/classfit/member/controller/MemberController.java
  src/main/java/classfit/example/classfit/member/controller/docs/MemberControllerDocs.java
  src/main/java/classfit/example/classfit/member/service/MemberService.java
  src/main/java/classfit/example/classfit/scoreReport/controller/ScoreReportController.java
  src/main/java/classfit/example/classfit/scoreReport/controller/docs/ScoreReportControllerDocs.java
  src/main/java/classfit/example/classfit/sms/controller/SendMessageController.java
  src/main/java/classfit/example/classfit/sms/controller/docs/SendMessageControllerDocs.java
  src/main/java/classfit/example/classfit/sms/service/SmsService.java
  src/main/java/classfit/example/classfit/student/controller/StudentController.java
  src/main/java/classfit/example/classfit/student/controller/docs/StudentControllerDocs.java
  src/main/java/classfit/example/classfit/studentExam/controller/ExamController.java
  src/main/java/classfit/example/classfit/studentExam/controller/docs/ExamControllerDocs.java
Labels: Docs, Refactor

#262 [Docs] 서비스 소개 자료 작성
  README.md
Labels: Docs
